{
  "timestamp": "2025-07-12T13:16:26.270437",
  "tests": {
    "unit": {
      "status": "passed",
      "output": "============================= test session starts ==============================\nplatform linux -- Python 3.11.13, pytest-7.4.3, pluggy-1.6.0 -- /usr/local/bin/python3.11\ncachedir: .pytest_cache\ndjango: version: 4.2.7\nrootdir: /app\nconfigfile: pytest.ini\nplugins: Faker-37.4.0, cov-4.1.0, django-4.7.0, anyio-4.9.0\ncollecting ... collected 37 items\n\ntests/unit/test_classification_models.py::TestClassificationRule::test_create_classification_rule PASSED [  2%]\ntests/unit/test_classification_models.py::TestClassificationRule::test_rule_increment_matches PASSED [  5%]\ntests/unit/test_classification_models.py::TestClassificationRule::test_rule_increment_successful_classifications PASSED [  8%]\ntests/unit/test_classification_models.py::TestClassificationRule::test_rule_success_rate_calculation PASSED [ 10%]\ntests/unit/test_classification_models.py::TestClassificationRule::test_rule_unique_name PASSED [ 13%]\ntests/unit/test_classification_models.py::TestClassificationModel::test_create_classification_model PASSED [ 16%]\ntests/unit/test_classification_models.py::TestClassificationModel::test_model_increment_predictions PASSED [ 18%]\ntests/unit/test_classification_models.py::TestClassificationResult::test_create_classification_result PASSED [ 21%]\ntests/unit/test_classification_models.py::TestClassificationResult::test_accept_classification PASSED [ 24%]\ntests/unit/test_classification_models.py::TestClassificationTrainingData::test_create_training_data PASSED [ 27%]\ntests/unit/test_classification_models.py::TestClassificationStatistic::test_create_classification_statistic PASSED [ 29%]\ntests/unit/test_classification_models.py::TestClassificationStatistic::test_statistic_success_rate_calculation PASSED [ 32%]\ntests/unit/test_news_models.py::TestCategoryModel::test_create_category PASSED [ 35%]\ntests/unit/test_news_models.py::TestCategoryModel::test_category_unique_name PASSED [ 37%]\ntests/unit/test_news_models.py::TestCategoryModel::test_category_unique_slug PASSED [ 40%]\ntests/unit/test_news_models.py::TestSubcategoryModel::test_create_subcategory PASSED [ 43%]\ntests/unit/test_news_models.py::TestSubcategoryModel::test_subcategory_category_slug_unique_together PASSED [ 45%]\ntests/unit/test_news_models.py::TestTagModel::test_create_tag PASSED     [ 48%]\ntests/unit/test_news_models.py::TestTagModel::test_tag_unique_name PASSED [ 51%]\ntests/unit/test_news_models.py::TestNewsModel::test_create_news PASSED   [ 54%]\ntests/unit/test_news_models.py::TestNewsModel::test_news_auto_word_count PASSED [ 56%]\ntests/unit/test_news_models.py::TestNewsModel::test_news_auto_reading_time PASSED [ 59%]\ntests/unit/test_news_models.py::TestNewsModel::test_news_auto_summary_generation PASSED [ 62%]\ntests/unit/test_news_models.py::TestNewsModel::test_news_increment_view_count PASSED [ 64%]\ntests/unit/test_news_models.py::TestNewsModel::test_news_increment_share_count PASSED [ 67%]\ntests/unit/test_news_models.py::TestNewsModel::test_news_external_id_unique PASSED [ 70%]\ntests/unit/test_news_models.py::TestNewsProcessingLog::test_create_processing_log PASSED [ 72%]\ntests/unit/test_news_serializers.py::TestCategorySerializer::test_serialize_category PASSED [ 75%]\ntests/unit/test_news_serializers.py::TestCategorySerializer::test_deserialize_category PASSED [ 78%]\ntests/unit/test_news_serializers.py::TestSubcategorySerializer::test_serialize_subcategory PASSED [ 81%]\ntests/unit/test_news_serializers.py::TestTagSerializer::test_serialize_tag PASSED [ 83%]\ntests/unit/test_news_serializers.py::TestNewsSerializers::test_news_list_serializer PASSED [ 86%]\ntests/unit/test_news_serializers.py::TestNewsSerializers::test_news_detail_serializer PASSED [ 89%]\ntests/unit/test_news_serializers.py::TestNewsSerializers::test_news_create_serializer PASSED [ 91%]\ntests/unit/test_news_serializers.py::TestNewsSerializers::test_news_update_serializer PASSED [ 94%]\ntests/unit/test_news_serializers.py::TestNewsSerializers::test_news_create_serializer_validation PASSED [ 97%]\ntests/unit/test_news_serializers.py::TestNewsSerializers::test_news_create_with_duplicate_external_id PASSED [100%]\n\n=============================== warnings summary ===============================\ntests/unit/test_classification_models.py:14\n  /app/tests/unit/test_classification_models.py:14: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_classification_models.py:80\n  /app/tests/unit/test_classification_models.py:80: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_classification_models.py:119\n  /app/tests/unit/test_classification_models.py:119: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_classification_models.py:172\n  /app/tests/unit/test_classification_models.py:172: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_classification_models.py:196\n  /app/tests/unit/test_classification_models.py:196: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_models.py:13\n  /app/tests/unit/test_news_models.py:13: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_models.py:53\n  /app/tests/unit/test_news_models.py:53: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_models.py:88\n  /app/tests/unit/test_news_models.py:88: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_models.py:114\n  /app/tests/unit/test_news_models.py:114: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_models.py:213\n  /app/tests/unit/test_news_models.py:213: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_serializers.py:15\n  /app/tests/unit/test_news_serializers.py:15: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_serializers.py:50\n  /app/tests/unit/test_news_serializers.py:50: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_serializers.py:65\n  /app/tests/unit/test_news_serializers.py:65: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\ntests/unit/test_news_serializers.py:79\n  /app/tests/unit/test_news_serializers.py:79: PytestUnknownMarkWarning: Unknown pytest.mark.unit - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.unit\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n\n---------- coverage: platform linux, python 3.11.13-final-0 ----------\nName                                                                           Stmts   Miss  Cover\n--------------------------------------------------------------------------------------------------\napps/__init__.py                                                                   0      0   100%\napps/authentication/__init__.py                                                    0      0   100%\napps/authentication/admin.py                                                      34      4    88%\napps/authentication/apps.py                                                       10      0   100%\napps/authentication/backends.py                                                   24     24     0%\napps/authentication/drf_authentication.py                                         38     38     0%\napps/authentication/migrations/0001_initial.py                                    11     11     0%\napps/authentication/migrations/__init__.py                                         0      0   100%\napps/authentication/models.py                                                     63      7    89%\napps/authentication/serializers.py                                                97     97     0%\napps/authentication/urls.py                                                       19     19     0%\napps/authentication/views.py                                                     104    104     0%\napps/classification/__init__.py                                                    0      0   100%\napps/classification/admin.py                                                     144     63    56%\napps/classification/apps.py                                                        7      0   100%\napps/classification/classifier.py                                                225    166    26%\napps/classification/migrations/0001_initial.py                                     8      8     0%\napps/classification/migrations/__init__.py                                         0      0   100%\napps/classification/models.py                                                    162      1    99%\napps/classification/serializers.py                                                87     87     0%\napps/classification/signals.py                                                    38      6    84%\napps/classification/tasks.py                                                     168    146    13%\napps/classification/urls.py                                                       12     12     0%\napps/classification/views.py                                                     168    168     0%\napps/demo/__init__.py                                                              0      0   100%\napps/demo/apps.py                                                                  5      0   100%\napps/demo/urls.py                                                                  4      4     0%\napps/demo/views.py                                                               167    167     0%\napps/news/__init__.py                                                              0      0   100%\napps/news/admin.py                                                                91     20    78%\napps/news/apps.py                                                                  7      0   100%\napps/news/filters.py                                                              62     62     0%\napps/news/management/__init__.py                                                   0      0   100%\napps/news/management/commands/__init__.py                                          0      0   100%\napps/news/management/commands/create_sample_data.py                               78     78     0%\napps/news/migrations/0001_initial.py                                              11     11     0%\napps/news/migrations/0002_remove_news_news_news_title_ad75b1_gin_and_more.py       5      5     0%\napps/news/migrations/0003_fix_external_id_constraint.py                            4      4     0%\napps/news/migrations/__init__.py                                                   0      0   100%\napps/news/models.py                                                              130      3    98%\napps/news/pagination.py                                                           15     15     0%\napps/news/serializers.py                                                          92      0   100%\napps/news/signals.py                                                              39      3    92%\napps/news/tasks.py                                                                93     93     0%\napps/news/urls.py                                                                 12     12     0%\napps/news/views.py                                                               149    149     0%\napps/notifications/__init__.py                                                     0      0   100%\napps/notifications/admin.py                                                      141     56    60%\napps/notifications/apps.py                                                         7      0   100%\napps/notifications/migrations/0001_initial.py                                      9      9     0%\napps/notifications/migrations/__init__.py                                          0      0   100%\napps/notifications/models.py                                                     202     64    68%\napps/notifications/providers.py                                                  140    106    24%\napps/notifications/serializers.py                                                129    129     0%\napps/notifications/signals.py                                                     37     25    32%\napps/notifications/tasks.py                                                      194    171    12%\napps/notifications/urls.py                                                        12     12     0%\napps/notifications/views.py                                                      211    211     0%\napps/webhooks/__init__.py                                                          0      0   100%\napps/webhooks/admin.py                                                           105     40    62%\napps/webhooks/apps.py                                                              7      0   100%\napps/webhooks/migrations/0001_initial.py                                           7      7     0%\napps/webhooks/migrations/__init__.py                                               0      0   100%\napps/webhooks/models.py                                                          124     30    76%\napps/webhooks/serializers.py                                                      81     81     0%\napps/webhooks/signals.py                                                          28     18    36%\napps/webhooks/tasks.py                                                           151    151     0%\napps/webhooks/urls.py                                                              9      9     0%\napps/webhooks/utils.py                                                           121    121     0%\napps/webhooks/views.py                                                           140    140     0%\n--------------------------------------------------------------------------------------------------\nTOTAL                                                                           4238   2967    30%\nCoverage JSON written to file coverage.json\n\n======================= 37 passed, 14 warnings in 25.03s =======================\n"
    },
    "integration": {
      "status": "failed",
      "error": "time=\"2025-07-12T13:16:43-03:00\" level=warning msg=\"/mnt/c/Users/pablo/JOTA/jota-news-system/docker-compose.yml: `version` is obsolete\"\n",
      "output": "============================= test session starts ==============================\nplatform linux -- Python 3.11.13, pytest-7.4.3, pluggy-1.6.0 -- /usr/local/bin/python3.11\ncachedir: .pytest_cache\ndjango: version: 4.2.7\nrootdir: /app\nconfigfile: pytest.ini\nplugins: Faker-37.4.0, cov-4.1.0, django-4.7.0, anyio-4.9.0\ncollecting ... collected 32 items\n\ntests/integration/test_news_api.py::TestNewsAPI::test_list_news_authenticated PASSED [  3%]\ntests/integration/test_news_api.py::TestNewsAPI::test_list_news_unauthenticated PASSED [  6%]\ntests/integration/test_news_api.py::TestNewsAPI::test_retrieve_news PASSED [  9%]\ntests/integration/test_news_api.py::TestNewsAPI::test_create_news PASSED [ 12%]\ntests/integration/test_news_api.py::TestNewsAPI::test_update_news PASSED [ 15%]\ntests/integration/test_news_api.py::TestNewsAPI::test_filter_news_by_category PASSED [ 18%]\ntests/integration/test_news_api.py::TestNewsAPI::test_search_news PASSED [ 21%]\ntests/integration/test_news_api.py::TestNewsAPI::test_mark_news_urgent PASSED [ 25%]\ntests/integration/test_news_api.py::TestNewsAPI::test_share_news PASSED  [ 28%]\ntests/integration/test_news_api.py::TestNewsAPI::test_get_related_news PASSED [ 31%]\ntests/integration/test_news_api.py::TestNewsAPI::test_advanced_search PASSED [ 34%]\ntests/integration/test_news_api.py::TestCategoryAPI::test_list_categories PASSED [ 37%]\ntests/integration/test_news_api.py::TestCategoryAPI::test_create_category PASSED [ 40%]\ntests/integration/test_news_api.py::TestCategoryAPI::test_category_statistics PASSED [ 43%]\ntests/integration/test_news_api.py::TestTagAPI::test_list_tags PASSED    [ 46%]\ntests/integration/test_news_api.py::TestTagAPI::test_create_tag PASSED   [ 50%]\ntests/integration/test_news_api.py::TestNewsPermissions::test_unauthenticated_read_access_allowed PASSED [ 53%]\ntests/integration/test_news_api.py::TestNewsPermissions::test_read_only_access_for_regular_users PASSED [ 56%]\ntests/integration/test_webhook_integration.py::TestWebhookEndpoints::test_webhook_source_crud PASSED [ 59%]\ntests/integration/test_webhook_integration.py::TestWebhookEndpoints::test_webhook_statistics PASSED [ 62%]\ntests/integration/test_webhook_integration.py::TestWebhookEndpoints::test_webhook_test_endpoint PASSED [ 65%]\ntests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_receive_valid_webhook PASSED [ 68%]\ntests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_receive_webhook_invalid_json PASSED [ 71%]\ntests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_receive_webhook_missing_required_fields PASSED [ 75%]\ntests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_webhook_signature_verification FAILED [ 78%]\ntests/integration/test_webhook_integration.py::TestWebhookDashboard::test_webhook_dashboard FAILED [ 81%]\ntests/integration/test_webhook_integration.py::TestWebhookProcessing::test_webhook_processing_task_triggered PASSED [ 84%]\ntests/integration/test_webhook_integration.py::TestWebhookProcessing::test_webhook_log_creation PASSED [ 87%]\ntests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_receive_webhook_invalid_source FAILED [ 90%]\ntests/integration/test_webhook_integration.py::TestWhatsAppWebhook::test_whatsapp_webhook_verification FAILED [ 93%]\ntests/integration/test_webhook_integration.py::TestWhatsAppWebhook::test_whatsapp_webhook_verification_invalid_token PASSED [ 96%]\ntests/integration/test_webhook_integration.py::TestWhatsAppWebhook::test_whatsapp_webhook_message_receive FAILED [100%]\n\n=================================== FAILURES ===================================\n_________ TestNewsWebhookReceiver.test_webhook_signature_verification __________\n\nself = <tests.integration.test_webhook_integration.TestNewsWebhookReceiver object at 0x71a42f952310>\nmock_verify = <MagicMock name='verify_webhook_signature' id='124948818684240'>\napi_client = <rest_framework.test.APIClient object at 0x71a3e9de9cd0>\nwebhook_source = <WebhookSource: Test Webhook Source>\nsample_webhook_data = {'author': 'Webhook Author', 'category_hint': 'test category', 'content': 'This is sample news content received via webhook. It contains enough text to be processed properly.', 'external_id': '58d2a7d0-23b6-4318-8be0-8d7fcd41aebd', ...}\n\n    @patch('apps.webhooks.utils.verify_webhook_signature')\n    def test_webhook_signature_verification(self, mock_verify, api_client, webhook_source, sample_webhook_data):\n        \"\"\"Test webhook signature verification.\"\"\"\n        webhook_source.requires_authentication = True\n        webhook_source.save()\n    \n        # Test with valid signature\n        mock_verify.return_value = True\n        url = reverse('webhooks:news_webhook', kwargs={'source_name': webhook_source.name})\n    \n        response = api_client.post(\n            url,\n            data=json.dumps(sample_webhook_data),\n            content_type='application/json',\n            HTTP_X_HUB_SIGNATURE_256='sha256=valid_signature'\n        )\n    \n>       assert response.status_code == status.HTTP_200_OK\nE       assert 401 == 200\nE        +  where 401 = <JsonResponse status_code=401, \"application/json\">.status_code\nE        +  and   200 = status.HTTP_200_OK\n\ntests/integration/test_webhook_integration.py:153: AssertionError\n---------------------------- Captured stderr setup -----------------------------\nINFO Webhook source created: Test Webhook Source\n------------------------------ Captured log setup ------------------------------\nINFO     apps.webhooks.signals:signals.py:24 Webhook source created: Test Webhook Source\n----------------------------- Captured stderr call -----------------------------\nINFO Webhook source updated: Test Webhook Source\nINFO Request started - POST /api/v1/webhooks/receive/Test Webhook Source/\nINFO Request completed - POST /api/v1/webhooks/receive/Test Webhook Source/ - 401\nWARNING Unauthorized: /api/v1/webhooks/receive/Test Webhook Source/\n------------------------------ Captured log call -------------------------------\nINFO     apps.webhooks.signals:signals.py:24 Webhook source updated: Test Webhook Source\n_________________ TestWebhookDashboard.test_webhook_dashboard __________________\n\nself = <tests.integration.test_webhook_integration.TestWebhookDashboard object at 0x71a42f96f490>\nauthenticated_client = <rest_framework.test.APIClient object at 0x71a3e9c4f090>\nwebhook_source = <WebhookSource: Test Webhook Source>\n\n    def test_webhook_dashboard(self, authenticated_client, webhook_source):\n        \"\"\"Test webhook dashboard endpoint.\"\"\"\n        url = reverse('webhooks:dashboard')\n>       response = authenticated_client.get(url)\n\ntests/integration/test_webhook_integration.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.11/site-packages/rest_framework/test.py:289: in get\n    response = super().get(path, data=data, **extra)\n/usr/local/lib/python3.11/site-packages/rest_framework/test.py:206: in get\n    return self.generic('GET', path, **r)\n/usr/local/lib/python3.11/site-packages/rest_framework/test.py:234: in generic\n    return super().generic(\n/usr/local/lib/python3.11/site-packages/django/test/client.py:609: in generic\n    return self.request(**r)\n/usr/local/lib/python3.11/site-packages/rest_framework/test.py:286: in request\n    return super().request(**kwargs)\n/usr/local/lib/python3.11/site-packages/rest_framework/test.py:238: in request\n    request = super().request(**kwargs)\n/usr/local/lib/python3.11/site-packages/django/test/client.py:891: in request\n    self.check_exception(response)\n/usr/local/lib/python3.11/site-packages/django/test/client.py:738: in check_exception\n    raise exc_value\n/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py:55: in inner\n    response = get_response(request)\n/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py:197: in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py:56: in wrapper_view\n    return view_func(*args, **kwargs)\n/usr/local/lib/python3.11/site-packages/django/views/generic/base.py:104: in view\n    return self.dispatch(request, *args, **kwargs)\n/usr/local/lib/python3.11/site-packages/rest_framework/views.py:509: in dispatch\n    response = self.handle_exception(exc)\n/usr/local/lib/python3.11/site-packages/rest_framework/views.py:469: in handle_exception\n    self.raise_uncaught_exception(exc)\n/usr/local/lib/python3.11/site-packages/rest_framework/views.py:480: in raise_uncaught_exception\n    raise exc\n/usr/local/lib/python3.11/site-packages/rest_framework/views.py:506: in dispatch\n    response = handler(request, *args, **kwargs)\n/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py:50: in handler\n    return func(*args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nrequest = <rest_framework.request.Request: GET '/api/v1/webhooks/dashboard/'>\n\n    @api_view(['GET'])\n    @permission_classes([IsAuthenticated])\n    @extend_schema(\n        summary=\"Get webhook dashboard data\",\n        description=\"Get aggregated webhook statistics for dashboard display.\"\n    )\n    def webhook_dashboard(request):\n        \"\"\"\n        Get webhook dashboard data.\n        \"\"\"\n        # Get recent statistics\n        today = timezone.now().date()\n        week_ago = today - timezone.timedelta(days=7)\n    \n        # Overall statistics\n        total_sources = WebhookSource.objects.filter(is_active=True).count()\n        total_logs = WebhookLog.objects.filter(created_at__date__gte=week_ago).count()\n        success_rate = WebhookLog.objects.filter(\n            created_at__date__gte=week_ago,\n            status='success'\n        ).count() / max(total_logs, 1) * 100\n    \n        # Recent activity\n        recent_logs = WebhookLog.objects.filter(\n            created_at__date__gte=week_ago\n        ).order_by('-created_at')[:10]\n    \n        # Source statistics\n        source_stats = []\n        for source in WebhookSource.objects.filter(is_active=True):\n            stats = WebhookStatistic.objects.filter(\n                source=source,\n                date__gte=week_ago\n            ).aggregate(\n>               total_requests=models.Sum('total_requests'),\n                successful_requests=models.Sum('successful_requests'),\n                failed_requests=models.Sum('failed_requests')\n            )\nE           NameError: name 'models' is not defined\n\napps/webhooks/views.py:406: NameError\n---------------------------- Captured stderr setup -----------------------------\nINFO Webhook source created: Test Webhook Source\n------------------------------ Captured log setup ------------------------------\nINFO     apps.webhooks.signals:signals.py:24 Webhook source created: Test Webhook Source\n----------------------------- Captured stderr call -----------------------------\nINFO Request started - GET /api/v1/webhooks/dashboard/\nERROR Request failed - GET /api/v1/webhooks/dashboard/ - name 'models' is not defined\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/views/generic/base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/apps/webhooks/views.py\", line 406, in webhook_dashboard\n    total_requests=models.Sum('total_requests'),\n                   ^^^^^^\nNameError: name 'models' is not defined\nERROR Internal Server Error: /api/v1/webhooks/dashboard/\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/views/generic/base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/apps/webhooks/views.py\", line 406, in webhook_dashboard\n    total_requests=models.Sum('total_requests'),\n                   ^^^^^^\nNameError: name 'models' is not defined\nINFO Request completed - GET /api/v1/webhooks/dashboard/ - 500\n_________ TestNewsWebhookReceiver.test_receive_webhook_invalid_source __________\n\nself = <tests.integration.test_webhook_integration.TestNewsWebhookReceiver object at 0x71a42f952150>\napi_client = <rest_framework.test.APIClient object at 0x71a3e9c31750>\nsample_webhook_data = {'author': 'Webhook Author', 'category_hint': 'test category', 'content': 'This is sample news content received via webhook. It contains enough text to be processed properly.', 'external_id': '58cb084b-ddac-4e37-bb80-3fd0e140947a', ...}\n\n    def test_receive_webhook_invalid_source(self, api_client, sample_webhook_data):\n        \"\"\"Test receiving webhook with invalid source.\"\"\"\n        url = reverse('webhooks:news_webhook', kwargs={'source_name': 'nonexistent'})\n    \n        response = api_client.post(\n            url,\n            data=json.dumps(sample_webhook_data),\n            content_type='application/json'\n        )\n    \n>       assert response.status_code == status.HTTP_404_NOT_FOUND\nE       assert 500 == 404\nE        +  where 500 = <JsonResponse status_code=500, \"application/json\">.status_code\nE        +  and   404 = status.HTTP_404_NOT_FOUND\n\ntests/integration/test_webhook_integration.py:104: AssertionError\n----------------------------- Captured stderr call -----------------------------\nINFO Request started - POST /api/v1/webhooks/receive/nonexistent/\nERROR Error processing webhook: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\nTraceback (most recent call last):\n  File \"/app/apps/webhooks/views.py\", line 220, in news_webhook\n    source = WebhookSource.objects.get(name=source_name, is_active=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 633, in get\n    num = len(clone)\n          ^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 380, in __len__\n    self._fetch_all()\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 330, in cursor\n    return self._cursor()\n           ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"/usr/local/lib/python3.11/site-packages/pytest_django/plugin.py\", line 798, in _blocking_wrapper\n    raise RuntimeError(\nRuntimeError: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\nINFO Request completed - POST /api/v1/webhooks/receive/nonexistent/ - 500\nERROR Internal Server Error: /api/v1/webhooks/receive/nonexistent/\n------------------------------ Captured log call -------------------------------\nERROR    apps.webhooks.views:views.py:291 Error processing webhook: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\nTraceback (most recent call last):\n  File \"/app/apps/webhooks/views.py\", line 220, in news_webhook\n    source = WebhookSource.objects.get(name=source_name, is_active=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 633, in get\n    num = len(clone)\n          ^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 380, in __len__\n    self._fetch_all()\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 330, in cursor\n    return self._cursor()\n           ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"/usr/local/lib/python3.11/site-packages/pytest_django/plugin.py\", line 798, in _blocking_wrapper\n    raise RuntimeError(\nRuntimeError: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\n____________ TestWhatsAppWebhook.test_whatsapp_webhook_verification ____________\n\nself = <tests.integration.test_webhook_integration.TestWhatsAppWebhook object at 0x71a42f9520d0>\napi_client = <rest_framework.test.APIClient object at 0x71a3e9cdfb90>\n\n    def test_whatsapp_webhook_verification(self, api_client):\n        \"\"\"Test WhatsApp webhook verification.\"\"\"\n        url = reverse('webhooks:whatsapp_webhook')\n    \n        params = {\n            'hub.mode': 'subscribe',\n            'hub.challenge': 'test_challenge_string',\n            'hub.verify_token': 'test_verify_token'\n        }\n    \n        response = api_client.get(url, params)\n    \n>       assert response.status_code == status.HTTP_200_OK\nE       assert 400 == 200\nE        +  where 400 = <HttpResponse status_code=400, \"text/html; charset=utf-8\">.status_code\nE        +  and   200 = status.HTTP_200_OK\n\ntests/integration/test_webhook_integration.py:184: AssertionError\n----------------------------- Captured stderr call -----------------------------\nINFO Request started - GET /api/v1/webhooks/whatsapp/\nINFO Request completed - GET /api/v1/webhooks/whatsapp/ - 400\nWARNING Bad Request: /api/v1/webhooks/whatsapp/\n__________ TestWhatsAppWebhook.test_whatsapp_webhook_message_receive ___________\n\nself = <tests.integration.test_webhook_integration.TestWhatsAppWebhook object at 0x71a42f93d950>\napi_client = <rest_framework.test.APIClient object at 0x71a3e9c6f710>\n\n    def test_whatsapp_webhook_message_receive(self, api_client):\n        \"\"\"Test receiving WhatsApp messages.\"\"\"\n        url = reverse('webhooks:whatsapp_webhook')\n    \n        whatsapp_data = {\n            'object': 'whatsapp_business_account',\n            'entry': [{\n                'id': 'entry_id',\n                'changes': [{\n                    'value': {\n                        'messaging_product': 'whatsapp',\n                        'metadata': {\n                            'phone_number_id': 'phone_id'\n                        },\n                        'messages': [{\n                            'id': 'message_id',\n                            'from': '5511999999999',\n                            'timestamp': '1234567890',\n                            'text': {\n                                'body': 'Hello from WhatsApp'\n                            },\n                            'type': 'text'\n                        }]\n                    },\n                    'field': 'messages'\n                }]\n            }]\n        }\n    \n        response = api_client.post(\n            url,\n            data=json.dumps(whatsapp_data),\n            content_type='application/json'\n        )\n    \n>       assert response.status_code == status.HTTP_200_OK\nE       assert 500 == 200\nE        +  where 500 = <JsonResponse status_code=500, \"application/json\">.status_code\nE        +  and   200 = status.HTTP_200_OK\n\ntests/integration/test_webhook_integration.py:236: AssertionError\n----------------------------- Captured stderr call -----------------------------\nINFO Request started - POST /api/v1/webhooks/whatsapp/\nERROR Error processing WhatsApp webhook: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\nTraceback (most recent call last):\n  File \"/app/apps/webhooks/views.py\", line 345, in whatsapp_webhook\n    source=WebhookSource.objects.get_or_create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 916, in get_or_create\n    return self.get(**kwargs), False\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 633, in get\n    num = len(clone)\n          ^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 380, in __len__\n    self._fetch_all()\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 330, in cursor\n    return self._cursor()\n           ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"/usr/local/lib/python3.11/site-packages/pytest_django/plugin.py\", line 798, in _blocking_wrapper\n    raise RuntimeError(\nRuntimeError: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\nINFO Request completed - POST /api/v1/webhooks/whatsapp/ - 500\nERROR Internal Server Error: /api/v1/webhooks/whatsapp/\n------------------------------ Captured log call -------------------------------\nERROR    apps.webhooks.views:views.py:368 Error processing WhatsApp webhook: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\nTraceback (most recent call last):\n  File \"/app/apps/webhooks/views.py\", line 345, in whatsapp_webhook\n    source=WebhookSource.objects.get_or_create(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 916, in get_or_create\n    return self.get(**kwargs), False\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 633, in get\n    num = len(clone)\n          ^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 380, in __len__\n    self._fetch_all()\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n              ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 330, in cursor\n    return self._cursor()\n           ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"/usr/local/lib/python3.11/site-packages/pytest_django/plugin.py\", line 798, in _blocking_wrapper\n    raise RuntimeError(\nRuntimeError: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\n=============================== warnings summary ===============================\ntests/integration/test_news_api.py:9\n  /app/tests/integration/test_news_api.py:9: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_news_api.py:152\n  /app/tests/integration/test_news_api.py:152: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_news_api.py:196\n  /app/tests/integration/test_news_api.py:196: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_news_api.py:223\n  /app/tests/integration/test_news_api.py:223: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_webhook_integration.py:14\n  /app/tests/integration/test_webhook_integration.py:14: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_webhook_integration.py:72\n  /app/tests/integration/test_webhook_integration.py:72: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_webhook_integration.py:168\n  /app/tests/integration/test_webhook_integration.py:168: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_webhook_integration.py:239\n  /app/tests/integration/test_webhook_integration.py:239: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\ntests/integration/test_webhook_integration.py:259\n  /app/tests/integration/test_webhook_integration.py:259: PytestUnknownMarkWarning: Unknown pytest.mark.integration - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html\n    @pytest.mark.integration\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n=========================== short test summary info ============================\nFAILED tests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_webhook_signature_verification\nFAILED tests/integration/test_webhook_integration.py::TestWebhookDashboard::test_webhook_dashboard\nFAILED tests/integration/test_webhook_integration.py::TestNewsWebhookReceiver::test_receive_webhook_invalid_source\nFAILED tests/integration/test_webhook_integration.py::TestWhatsAppWebhook::test_whatsapp_webhook_verification\nFAILED tests/integration/test_webhook_integration.py::TestWhatsAppWebhook::test_whatsapp_webhook_message_receive\n=================== 5 failed, 27 passed, 9 warnings in 8.46s ===================\n"
    },
    "api__api_v1_news_categories_": {
      "status": "passed",
      "response_code": 200
    },
    "api__api_v1_news_tags_": {
      "status": "passed",
      "response_code": 200
    },
    "api__api_v1_news_articles_": {
      "status": "passed",
      "response_code": 200
    },
    "api__api_docs_": {
      "status": "passed",
      "response_code": 200
    },
    "api__metrics": {
      "status": "passed",
      "response_code": 200
    },
    "api__celery_metrics_": {
      "status": "passed",
      "response_code": 200
    },
    "api__business_metrics_": {
      "status": "passed",
      "response_code": 200
    },
    "api__security_metrics_": {
      "status": "passed",
      "response_code": 200
    }
  },
  "demos": {
    "news_creation": {
      "status": "passed"
    },
    "classification": {
      "status": "passed"
    },
    "webhook_processing": {
      "status": "failed",
      "error": "HTTP 401"
    },
    "monitoring_metrics": {
      "status": "passed"
    }
  },
  "performance": {
    "/api/v1/news/articles/": {
      "avg_response_time": 0.027346539497375488,
      "max_response_time": 0.031172513961791992,
      "min_response_time": 0.02553272247314453,
      "requests_count": 10
    },
    "/api/v1/news/categories/": {
      "avg_response_time": 0.023358964920043947,
      "max_response_time": 0.024804115295410156,
      "min_response_time": 0.022294998168945312,
      "requests_count": 10
    },
    "/health/": {
      "avg_response_time": 0.0039777994155883786,
      "max_response_time": 0.004240751266479492,
      "min_response_time": 0.003739595413208008,
      "requests_count": 10
    }
  },
  "health_checks": {
    "API Server": {
      "status": "healthy",
      "response_time": 0.004717
    },
    "Grafana": {
      "status": "healthy",
      "response_time": 0.002224
    },
    "Celery Monitoring": {
      "status": "healthy",
      "response_time": 1.056289
    },
    "Business Metrics": {
      "status": "healthy",
      "response_time": 0.018404
    },
    "Security Monitoring": {
      "status": "healthy",
      "response_time": 0.016703
    }
  },
  "monitoring": {
    "grafana": {
      "status": "available",
      "dashboard_count": 5,
      "dashboards": [
        {
          "id": 5,
          "uid": "celery-dashboard",
          "orgId": 1,
          "title": "Celery Task Monitoring",
          "uri": "db/celery-task-monitoring",
          "url": "/d/celery-dashboard/celery-task-monitoring",
          "slug": "",
          "type": "dash-db",
          "tags": [
            "celery",
            "monitoring",
            "tasks"
          ],
          "isStarred": false,
          "sortMeta": 0,
          "isDeleted": false
        },
        {
          "id": 4,
          "uid": "business-dashboard",
          "orgId": 1,
          "title": "JOTA News - Business Metrics",
          "uri": "db/jota-news-business-metrics",
          "url": "/d/business-dashboard/jota-news-business-metrics",
          "slug": "",
          "type": "dash-db",
          "tags": [
            "business",
            "jota",
            "metrics",
            "news"
          ],
          "isStarred": false,
          "sortMeta": 0,
          "isDeleted": false
        },
        {
          "id": 3,
          "uid": "security-dashboard",
          "orgId": 1,
          "title": "JOTA News - Security Monitoring",
          "uri": "db/jota-news-security-monitoring",
          "url": "/d/security-dashboard/jota-news-security-monitoring",
          "slug": "",
          "type": "dash-db",
          "tags": [
            "auth",
            "jota",
            "monitoring",
            "security"
          ],
          "isStarred": false,
          "sortMeta": 0,
          "isDeleted": false
        },
        {
          "id": 1,
          "uid": "jota-news-complete",
          "orgId": 1,
          "title": "JOTA News System - Complete Dashboard",
          "uri": "db/jota-news-system-complete-dashboard",
          "url": "/d/jota-news-complete/jota-news-system-complete-dashboard",
          "slug": "",
          "type": "dash-db",
          "tags": [
            "jota",
            "monitoring",
            "news"
          ],
          "isStarred": false,
          "sortMeta": 0,
          "isDeleted": false
        },
        {
          "id": 2,
          "uid": "redis-dashboard",
          "orgId": 1,
          "title": "Redis Dashboard",
          "uri": "db/redis-dashboard",
          "url": "/d/redis-dashboard/redis-dashboard",
          "slug": "",
          "type": "dash-db",
          "tags": [
            "cache",
            "jota",
            "redis"
          ],
          "isStarred": false,
          "sortMeta": 0,
          "isDeleted": false
        }
      ]
    }
  },
  "summary": {
    "total_tests": 10,
    "passed_tests": 9,
    "failed_tests": 1,
    "success_rate": 90.0,
    "execution_time": "2025-07-12T13:17:07.954369"
  }
}